In [4]:
n=int(input())
l=input().split()[:n]
s=0
for i in l:
    s += int(i[len(i)//2])
print(s)

3
56789 546 451
16


njbjbjlnrb
vkb aje 

In [1]:
import numpy as np
dir(np) #directory of numpy

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [2]:
np.__version__ #version of numpy module


'1.15.1'

### Numpy
- means numerical python
- array() is the submodule in numpy module
- np.array(iterable)

In [6]:
print(np.array([2,3,45,43]))

[ 2  3 45 43]


In [4]:
#tuple into array
t=np.array((3,2,3,1))
print(t)

[3 2 3 1]


In [7]:
t

array([3, 2, 3, 1])

In [8]:
ar=np.array([67.0,34,1,2,67],dtype="int")
print(ar)

[67 34  1  2 67]


In [11]:
ar=np.array([67,9,8,7],dtype="float")
print(ar)

[67.  9.  8.  7.]


In [12]:
print(np.array(range(1,10)))

[1 2 3 4 5 6 7 8 9]


In [13]:
ar.ndim #dimensions of array

1

In [14]:
li=np.array([[9,78,65],[5,4,98]])
print(li)

[[ 9 78 65]
 [ 5  4 98]]


In [15]:
li.size #total number of elements

6

In [16]:
li.shape #(row,col)

(2, 3)

In [17]:
li.dtype

dtype('int32')

In [18]:
d3=np.array([2,3,4],ndmin=5)
print(d3)

[[[[[2 3 4]]]]]


In [19]:
l=np.eye(5)
print(l)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
ar=np.array([23,1,2,3],dtype="str")
ar

array(['23', '1', '2', '3'], dtype='<U2')

In [23]:
ar=np.array([[[2,3,4],[1,2,3]]])
ar

array([[[2, 3, 4],
        [1, 2, 3]]])

In [24]:
li.shape

(2, 3)

In [25]:
z=np.zeros((4,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
o=np.ones(5)
o

array([1., 1., 1., 1., 1.])

In [27]:
o=np.ones((3,4))
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
f=np.full(4,"hi")
f

array(['hi', 'hi', 'hi', 'hi'], dtype='<U2')

In [30]:
f.fill("hey")
f

array(['he', 'he', 'he', 'he'], dtype='<U2')

In [31]:
ln=np.linspace(10,200 ,13)
print(ln)

[ 10.          25.83333333  41.66666667  57.5         73.33333333
  89.16666667 105.         120.83333333 136.66666667 152.5
 168.33333333 184.16666667 200.        ]


In [32]:
200/13

15.384615384615385

In [33]:
ar=np.arange(25)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ar=np.arange(1,8,3)
ar

array([1, 4, 7])

In [40]:
ar=np.array([1,2,3,4,5,6,7,89,73,1,4,5])
ar.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7, 89],
       [73,  1,  4,  5]])

In [41]:
arr=np.arange(100,50,-4)
arr

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52])

#### random()
- used to generate random integer in a range
- random.randint()

In [2]:
import numpy as np
rn=np.random.randint(10)
rn

9

In [3]:
#multiple random values
lw,lu=int(input()),int(input())
ri=np.random.randint(lw,lu,8)
ri.reshape(2,4)

2
10


array([[9, 5, 7, 8],
       [3, 5, 5, 4]])

In [10]:
np.random.random((2,3)) #random int b/w -1 and 1 of size(2,3)

array([[0.96076573, 0.34988037, 0.75579355],
       [0.79466184, 0.04182501, 0.14730118]])

In [5]:
np.random.rand(4,3) #size

array([[0.64550999, 0.93009425, 0.77318944],
       [0.31896894, 0.40940906, 0.2532681 ],
       [0.85767796, 0.33132671, 0.56148464],
       [0.32330327, 0.49604205, 0.57765739]])

In [8]:
np.random.randn(4,3) #between -1 and 1

array([[ 0.49275482,  1.20950271,  1.51759257],
       [-0.21534006,  0.44766889,  0.66190247],
       [ 0.51433402, -0.16485065,  0.19449301],
       [ 0.40391182,  0.9553259 ,  0.35026914]])

In [11]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

### Accessing the array elements
- using index
- index is of 3 types
- +ve indexing, -ve indexing and fancy indexing
  -  +ve index :traverse from left to right and
  -  starts from 0 and goes upto len(it)-1
  -  -ve index:from right to left
  -  starts from -1 and upto -infinite
  -  fancy: condition based index

In [13]:
rn=np.random.randint(50,200,25).reshape(5,-1)
rn

array([[155, 121, 144, 147, 124],
       [ 62,  94, 178, 155,  51],
       [125, 110,  64, 130,  80],
       [176, 101,  69, 123, 153],
       [153, 123,  50,  79, 135]])

In [18]:
ar=np.random.randint(1,7,4).reshape(-2,2)
ar

array([[3, 6],
       [5, 3]])

In [19]:
rn[3]

array([176, 101,  69, 123, 153])

In [20]:
rn[:]

array([[155, 121, 144, 147, 124],
       [ 62,  94, 178, 155,  51],
       [125, 110,  64, 130,  80],
       [176, 101,  69, 123, 153],
       [153, 123,  50,  79, 135]])

In [21]:
rn[::]

array([[155, 121, 144, 147, 124],
       [ 62,  94, 178, 155,  51],
       [125, 110,  64, 130,  80],
       [176, 101,  69, 123, 153],
       [153, 123,  50,  79, 135]])

In [22]:
rn[::-1]

array([[153, 123,  50,  79, 135],
       [176, 101,  69, 123, 153],
       [125, 110,  64, 130,  80],
       [ 62,  94, 178, 155,  51],
       [155, 121, 144, 147, 124]])

In [23]:
rn[::2]

array([[155, 121, 144, 147, 124],
       [125, 110,  64, 130,  80],
       [153, 123,  50,  79, 135]])

In [26]:
rn[:,1:4]

array([[121, 144, 147],
       [ 94, 178, 155],
       [110,  64, 130],
       [101,  69, 123],
       [123,  50,  79]])

In [31]:
for n in rn[:,1:4]:
    for i in n:
        if(i%2==0):
            print(i)

144
94
178
110
64
130
50


In [36]:
n=np.arange(50,100,25).reshape(5,-1)
n

ValueError: cannot reshape array of size 2 into shape (5,newaxis)

In [38]:
rn<150

array([[False,  True,  True,  True,  True],
       [ True,  True, False, False,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True,  True]])

In [39]:
rn[::2,::2]

array([[155, 144, 124],
       [125,  64,  80],
       [153,  50, 135]])

In [40]:
rn

array([[155, 121, 144, 147, 124],
       [ 62,  94, 178, 155,  51],
       [125, 110,  64, 130,  80],
       [176, 101,  69, 123, 153],
       [153, 123,  50,  79, 135]])

In [42]:
rn[rn<150]

array([121, 144, 147, 124,  62,  94,  51, 125, 110,  64, 130,  80, 101,
        69, 123, 123,  50,  79, 135])

In [43]:
print(rn+ar)

ValueError: operands could not be broadcast together with shapes (5,5) (2,2) 

In [45]:
nk=np.random.randint(10,50,25).reshape(5,-1)
nk

array([[39, 49, 20, 39, 14],
       [42, 16, 15, 19, 30],
       [23, 42, 27, 19, 27],
       [19, 21, 32, 13, 11],
       [16, 30, 33, 14, 42]])

In [46]:
rn+nk

array([[194, 170, 164, 186, 138],
       [104, 110, 193, 174,  81],
       [148, 152,  91, 149, 107],
       [195, 122, 101, 136, 164],
       [169, 153,  83,  93, 177]])

In [47]:
rn-nk

array([[116,  72, 124, 108, 110],
       [ 20,  78, 163, 136,  21],
       [102,  68,  37, 111,  53],
       [157,  80,  37, 110, 142],
       [137,  93,  17,  65,  93]])

In [48]:
rn*nk

array([[6045, 5929, 2880, 5733, 1736],
       [2604, 1504, 2670, 2945, 1530],
       [2875, 4620, 1728, 2470, 2160],
       [3344, 2121, 2208, 1599, 1683],
       [2448, 3690, 1650, 1106, 5670]])

In [49]:
rn.sum()

2902

In [50]:
rn.mean()

116.08

In [51]:
rn.max()

178

In [52]:
rn.min()

50

In [53]:
print(sum(rn))

[671 549 505 634 543]


In [54]:
np.exp(np.log(1))

1.0

In [55]:
np.log(np.exp(1))

1.0

In [57]:
li,li2=[9,3,1],[4,10,4]
new=[]
for a,b in zip(li,li2):
    if a>b:
        new.append(a)
    else:
        new.append(b)
new

[9, 10, 4]